### ISSUE TITLE
Automated check for PR Title  

### ISSUE THREAD

**Issue by tarangverma** [keptn-sandbox/datadog-service#121]
Since new contributors who has not contributed to keptn previously do not know the PR title style keptn follows.
This is to automate the PR title check whenever a new PR is created.

**Comment by vadasambar** [comment]
To supplement the above description:
We want our contributors to follow the [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/#summary) style for PR titles. Example:
```
chore: automate PR check
```
We want to support the following types (including `chore`):
```
            feat
            fix
            build
            chore
            ci
            docs
            perf
            refactor
            revert
            style
            test
```
and the following scopes:
```
            docs
            tests
            ci
            chart
            core
            examples
```
